{
    "name": "ERP Agent",
    "version": "1.0.0",
    "summary": "AI Assistant",
    "installable": True,
    "application": True,
    "depends": ["web", "sale_management", "purchase", "account"],
    "external_dependencies": {
        "python": [
            "django",
            "corsheaders",
            "uvicorn",
            "loguru",
            "nanobot",
            "litellm",
            "dotenv",
            "yaml",
            "aiohttp",
            "json_repair",
        ],
    },
    "post_load": "start",
    "data": [
        "security/ir.model.access.csv",
        "security/erp_agent_security.xml",
        "views/erp_agent_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "erp_agent/static/src/lib/marked.min.js",
            "erp_agent/static/src/lib/purify.min.js",
            "erp_agent/static/src/components/AgentSettings/AgentSettings.js",
            "erp_agent/static/src/components/AgentSettings/AgentSettings.xml",
            "erp_agent/static/src/components/AgentSettings/AgentSettings.scss",
            "erp_agent/static/src/components/ErpAgentChat/chatService.js",
            "erp_agent/static/src/components/ErpAgentChat/ErpAgentChat.js",
            "erp_agent/static/src/components/ErpAgentChat/ErpAgentChat.xml",
            "erp_agent/static/src/components/ErpAgentChat/ErpAgentChat.scss",
            "erp_agent/static/src/components/AgentWidget/AgentWidget.js",
            "erp_agent/static/src/components/AgentWidget/AgentWidget.xml",
            "erp_agent/static/src/components/AgentWidget/AgentWidget.scss",
            "erp_agent/static/src/dashboard/Dashboard.js",
            "erp_agent/static/src/dashboard/Dashboard.xml",
            "erp_agent/static/src/dashboard/Dashboard.scss",
        ],
    },
}
