# Generated by Django 6.0.2 on 2026-02-23 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("transaction", "Transaction"),
                            ("analytics", "Analytics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("instructions", models.TextField()),
                ("allowed_tools", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intent", models.CharField(max_length=500)),
                ("agent_name", models.CharField(max_length=255)),
                ("tool_called", models.CharField(max_length=255)),
                ("input_params", models.JSONField(default=dict)),
                ("output", models.JSONField(default=dict)),
                ("erp_record_ref", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OutputArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("chart", "Chart"),
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("text", "Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("format", models.CharField(max_length=50)),
                ("storage_path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
