# Generated by Django 6.0.3 on 2026-03-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_remove_output_artifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
