# Generated by Django 6.0.3 on 2026-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_agentaction_source_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='steps',
            field=models.JSONField(default=list),
        ),
    ]
