# Generated by Django 6.0.3 on 2026-04-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_agenttemplate_description_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttemplate',
            name='requires_write_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenttemplate',
            name='tool_config',
            field=models.JSONField(default=dict),
        ),
    ]
